### ISSUE TITLE
Studio Layout

### ISSUE THREAD

**Issue by nelsonic** [dwyl/studio#27]
The dimensions of the studio are **`3595 x 2547mm`**. This is either _tiny_ or _massive_ depending on your perspective.
If you watch Matthew Perks (***DIY Perks***) Studio Tour: https://github.com/dwyl/studio/issues/2 you'll see just how much can be done in a small space!
[![image](https://user-images.githubusercontent.com/194400/88546867-e221a300-d014-11ea-8857-bab0257bb3ab.png)](https://youtu.be/Z0oGIc8dvJ4)
Obviously this shot shows how messy it can get if you don't have a system for organising things.
He 3 distinct work areas but has to keep setting up and taring down for shots which he says take a lot of time:

![image](https://user-images.githubusercontent.com/194400/88548995-b18f3880-d017-11ea-83c5-250e2bc47597.png)

As much as I love [minimalism](https://en.wikipedia.org/wiki/Minimalism) in the _rest_ of the house, I think there needs to be a careful balance when it comes to maximising the space available to get everything done that needs to be done in the Studio. Specifically:

## 3 Distinct Work Areas: Compose, Record, Edit

1. **Recording Video + Audio** in a low noise environment
2. **Editing video** and being able to playback using Studio Monitors (Speakers). I mostly use headphones, but in the "final cut" (_before exporting_) it's a good idea to switch to speakers to check.
3. **Music Practicing, Composing and Recording** without creating noise in the house.

With these 3 activities in mind, I propose having 3 _separate_ work stations to _minimise_ setup/switching time:

1. **Sit/Stand desk** for Recording/Streaming Video permanently rigged with a **1080p Monitor**, **Sony A7 Camera** (in "Web Cam" mode) https://github.com/dwyl/video/issues/81 (through the **Teleprompter** https://github.com/dwyl/studio/issues/12), **Lights** #26 and **Microphone** https://github.com/dwyl/studio/issues/25 for [Piece to camera](https://en.wikipedia.org/wiki/Piece_to_camera) recording. 
2. **Video Editing Sitting Desk** with comfortable/ergonomic chair permanently setup for Editing video with minimal friction. Editor Keys Keyboard, Contour Shuttle, 4k Screen Connected to MacBook Pro https://github.com/dwyl/video/issues/55#issuecomment-445800176
3. **Music Making Station** (_another sitting desk_) with the Midi Controller at the correct height https://github.com/nelsonic/learn-music/issues/34
4. ***Optional*** **Overhead Rig** for filming electronics tutorials which I expect to do a few for smart home, aquaponics etc.

My main priority is getting the sit/stand desk setup for recording video tutorials. 
But having the rest of the layout in mind is helpful so that everything fits together once finished.

## Todo

+ [ ] Measure the _existing_ IKEA tables and see if/how we can fit 3 or 4 desks in the Studio
+ [ ] Draw the layout
+ [ ] Create the Stand/Sit Recording Desk Setup.
+ [ ] #51
+ [ ] Measure and figure out if we can mount the Midi controller on a shelf under the Sit/Stand desk.
+ [ ] Setup Camera #29

**Comment by nelsonic** [comment]
Tom Buck recently published:
Desk Setup Tour for Videos, Podcasts, & Streaming! https://youtu.be/uhxBX9VuOHY
[![image](https://user-images.githubusercontent.com/194400/175347009-ad345170-df1f-4565-9a49-bf22500ca753.png)](https://youtu.be/uhxBX9VuOHY)

Going to watch it this evening and see if there are an insights. 💭
