### ISSUE TITLE
Setup Sony A7 as Webcam for Zoom Video Calls with Teleprompter

### ISSUE THREAD

**Issue by nelsonic** [dwyl/studio#29]
Now that the Tripod Head https://github.com/dwyl/studio/issues/28#issuecomment-677893246 for mounting the A7 to the desk has arrived, I can proceed with the setup!

# Todo

+ [ ] Use Manfrotto 190 Tripod to determine the correct height for mounting the Camera at eye-level.
+ [ ] Create "shelf" for mounting the camera to the Sit-stand desk
+ [ ] Setup Teleprompter #12 with iPad Pro 10.5"
+ [ ] Connect Sony A7 to _dedicated_ **MacMini i7** via USB cable. instructions: https://github.com/dwyl/video/issues/81
+ [ ] Allow for head-on and angled camera angle. 
+ [ ] Test with Zoom!
  + [ ] Test with Green Screen (wall).
