### ISSUE TITLE
Mini Monitor Screen for Teleprompter

### ISSUE THREAD

**Issue by nelsonic** [dwyl/studio#30]
# _Context_

Using the iPad for Teleprompter https://github.com/dwyl/studio/issues/12#issuecomment-688843749  is _great_ for scripted content. ✅ 
I've recently found myself wanting to transfer a Zoom/Teams Call to the "A Camera" instead of the Web Cam and that's where the iPad is of limited use ... I cannot use "Side Car" on my Mac (Mid 2015 MacBook Pro 15" https://github.com/nelsonic/nelsonic.github.io/issues/371#issuecomment-463151626 _that I use for my "day job"_) so in order to use the iPad as a second screen I have to use Duet Display https://github.com/dwyl/remote-working/issues/32#issuecomment-489340229 which sadly is _suuuper_ laggy when it comes to video. When using Zoom/Teams there is a 2-3 second delay from when I hear the voice to when I see the person's mouth move; it's basically unusable. 

What I want is a dedicated mini (10 inch) monitor with **`1080p`** resolution that I can use as a "second display" and shift my Teams/Zoom calls to so that I can look directly at the "A Camera" when on meetings. Sadly, I spend 2-5 hours in meetings each day; _never_ less than **2 hours**. I really want to _maximise_ the quality of my presence both audio and video and using the Teleprompter seems like a good plan to up my game. 

# Todo

+ [x] Measure the exact dimensions of the reflective glass and "holder" of the Teleprompter to determine the maximum screen size I can get. --> Holder Height: 195mm (this is the constraining dimension), then the glass Width is 221mm but can accomodate a larger screen because it's a mirror; i.e. you can always look to either side in a mirror to see the rest of the "reflected world". 
+ [ ] Research
+ [ ] Order the screen
+ [ ] Wait patiently for it to arrive
+ [ ] Install & use the screen!
  + [ ] Thinking of using the mini screen with the HDMI splitter so that it exactly mirrors my "main" monitor. 

https://www.amazon.es/Computadora-Pantalla-Panor%C3%A1mica-Pulgadas-100-240V/dp/B091DKKJ18/
![image](https://user-images.githubusercontent.com/194400/131187835-44760007-892b-422a-88ca-6a55e629b824.png)

Sadly the listing does not have precise dimensions, so I'm dubious of the resolution being **`1080p`**. 💭

**Comment by nelsonic** [comment]
https://www.amazon.es/Pulgadas-1920x1080-Altavoces-Integrados-Raspberry/dp/B08JV27YCK
![image](https://user-images.githubusercontent.com/194400/131229153-74654c7f-0eed-4e8a-aedf-cb8f21667ce4.png)

**Comment by nelsonic** [comment]
To be 100% clear: the only reason I search for products on Amazon is because I know they won't get stuck in customs or incur ridiculous import duties. I've bought things from China/USA/etc. in the past from various websites and had _horrible_ experiences of items being stuck in customs for _weeks_, being returned to sender or having to _drive_ a 40min round trip to some random depot to collect stuff. It's a _huge_ waste of time. I value my time. So I use Amazon. 💭 

This monitor would be _perfect_ and has a great price but cannot be delivered to PT!! 🤦 
https://www.amazon.es/-/pt/dp/B085ZBP7YD/
<img width="1719" alt="mini-monitor-no-delivery" src="https://user-images.githubusercontent.com/194400/131246181-5583db5a-944f-48fa-b07c-3dc48296c093.png">

A bit of googling and it looks like this is it:
https://www.elecrow.com/10-1-inch-1920x1080-resolution-hdmi-vga-ips-ps3-ps4-gaming-screen-with-build-in-speakers-for-raspberry-pi-b-2b-3b-xbox-windows-7-8-10.html
![image](https://user-images.githubusercontent.com/194400/131246537-11de7288-e5ec-489e-a587-d451ea86639b.png)

This is quite a lot more than I wanted to spend (_especially because it's without VAT/IVA so the full price will be more like €210!_) but it looks like a good quality panel: https://www.amazon.es/-/pt/dp/B08P23KYN6/
![image](https://user-images.githubusercontent.com/194400/131246049-095956ec-82d6-464e-bd49-23bc309e11b1.png)

It's _very_ clearly a case of white-label product as this one looks _identical_ but the brand is "Tosuny" 🙄 
https://www.amazon.es/dp/B088BMHPLG/
![image](https://user-images.githubusercontent.com/194400/131246096-11f69e19-67b8-43d3-9ccf-7f8ec87f697f.png)

Need to get some precise measurements of the "Tablet Holder" that attaches to the Teleprompter before I can place an order. ⏳ 
Time to get out the Measuring Tape & Callipers. 📏

**Comment by nelsonic** [comment]
On re-measuring the **width** (_the constraining dimension_) of the teleprompter screen holder, it's **195mm**. So the 11.6 Inch display will fit:
https://www.elecrow.com/elecrow-11-6-inch-1920x1080-hdmi-1080p-led-display-for-raspberry-pi.html

![image](https://user-images.githubusercontent.com/194400/131265780-d95b628a-4edc-4404-8bcd-0fe20596bea4.png)

![image](https://user-images.githubusercontent.com/194400/131265816-442ef470-8a29-4151-b28c-db59dc4341d8.png)

**Comment by nelsonic** [comment]
Ordering the 11.6" display ...
Shipping is $20! 💸 

![elecrow-extortionate-shipping-cost](https://user-images.githubusercontent.com/194400/131662281-e5755a5a-5b3a-40d0-a874-581de83a0b6e.png)

Total is €133 ... going to double-check Amazon to see if there's anything else I can get instead at this price point.

**Comment by nelsonic** [comment]
I'm fairly certain that this order will be dispatched from China and thus will be intercepted by customs and incur IVA/VAT ...
