### ISSUE TITLE
Storage Box (Laser-cut. Hand-assembled + Finished)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/studio#54]
Need to build a sturdy plywood box of `10mm` ply to store various items. 

Features (should):

+ [ ] Fit an `A4` sheet of paper with some space around.
+ [ ] Exterior Height: `150mm`
+ [ ] Prevent dust from entering (lid should form a reasonably tight seal
+ [ ] Built-in hinge (like on the https://github.com/nelsonic/vinyl-record-carry-storage-box ) 
+ [ ] No handles required

**Comment by nelsonic** [comment]
148.5 x 210 mm -> 160 x 220
